---

- name: upgrade all packages 
  yum:
    name: "*"
    state: latest


- name: Install epel package
  package: 
    name: epel-release
    state: present


- name: Install htop
  package: 
    name: htop
    state: present


