
- hosts: centos-servers
  remote_user: root
  roles:
    - centos


- hosts: fedora-servers
  remote_user: root
  roles:
    - fedora


- hosts: ubuntu-servers
  become: yes
  become_user: seawolf
  become_method: sudo
  roles:
    - ubuntu

- hosts: debian-servers
  become: yes
  roles:
    - debian
